#!/usr/bin/env python
"""
Build script: Converts all .html template files into an embedded Python module.

Vercel's Python runtime does not reliably include .html files in the serverless
function bundle. This script generates a Python module that stores all template
content as Python string constants using repr(), which can then be loaded by
the EmbeddedTemplateLoader at runtime.

Usage:
    python build_embedded_templates.py

The generated file `src/apps/esppa/templates_embedded.py` is imported by the
custom template loader as a fallback when standard loaders fail.
"""

import os
import sys
import pathlib
import glob


def main():
    script_dir = pathlib.Path(__file__).resolve().parent
    src_dir = script_dir / 'src'

    if not src_dir.exists():
        print(f"Error: src/ directory not found at {src_dir}")
        print("Make sure you're running this from the project root.")
        sys.exit(1)

    output_file = src_dir / 'apps' / 'esppa' / 'templates_embedded.py'

    # Collect all .html template files from both template directories
    template_dirs = [
        src_dir / 'apps' / 'esppa' / 'templates',
        src_dir / 'templates',
    ]

    all_templates = {}
    for tdir in template_dirs:
        if tdir.exists():
            for fpath in sorted(tdir.rglob('*.html')):
                relative = fpath.relative_to(tdir)
                try:
                    content = fpath.read_text(encoding='utf-8')
                    # Normalize to forward slashes for cross-platform compatibility
                    # (Windows uses backslashes, Linux/Mac use forward slashes)
                    key = str(relative).replace('\\', '/')
                    all_templates[key] = content
                    print(f"  [OK] {relative}")
                except Exception as e:
                    print(f"  [ERR] {relative}: {e}")

    # Generate Python module using repr() for safe encoding
    lines = [
        '# Auto-generated by build_embedded_templates.py',
        '# Do not edit manually -- regenerate with: python build_embedded_templates.py',
        '',
        '"""',
        'Embedded HTML templates for Vercel deployment.',
        '',
        'Template content is stored as string constants to ensure they are',
        'included in the Vercel serverless function bundle (which only',
        'includes .py files by default).',
        '"""',
        '',
        'TEMPLATES = {',
    ]

    for name, content in sorted(all_templates.items()):
        # Use repr() for safe, lossless encoding of any template content
        lines.append(f'    {name!r}: {content!r},')

    lines.append('}')
    content = '\n'.join(lines)

    # Write the output file
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(content, encoding='utf-8')
    print(f"\n[DONE] Generated {output_file}")
    print(f"       Embedded {len(all_templates)} template(s)")
    return 0


if __name__ == '__main__':
    sys.exit(main())
