# Generated by Django 4.2.7 on 2025-08-06 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("years_at_company", models.IntegerField()),
                ("performance_score", models.FloatField()),
                ("monthly_salary", models.FloatField()),
                ("monthly_salary_inr", models.IntegerField()),
                ("hire_date", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
                ("education_level", models.CharField(max_length=50)),
                ("work_hours_per_week", models.IntegerField()),
                ("projects_handled", models.IntegerField()),
                ("overtime_hours", models.IntegerField()),
                ("sick_days", models.IntegerField()),
                ("remote_work_frequency", models.FloatField()),
                ("team_size", models.IntegerField()),
                ("training_hours", models.IntegerField()),
                ("promotions", models.IntegerField()),
                ("employee_satisfaction_score", models.FloatField()),
                ("resigned", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("random_forest", "Random Forest"),
                            ("logistic_regression", "Logistic Regression"),
                            ("linear_regression", "Linear Regression"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField()),
                ("prediction_result", models.FloatField()),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("error_rate", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("department", "Department Analysis"),
                            ("performance", "Performance Analysis"),
                            ("salary", "Salary Analysis"),
                            ("overtime", "Overtime Analysis"),
                            ("satisfaction", "Satisfaction Analysis"),
                            ("overall", "Overall Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("chart_type", models.CharField(max_length=50)),
                ("chart_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
