"""
Custom template loader that reads templates from the embedded Python module.

Vercel's Python runtime does not reliably include .html files in the serverless
function bundle. This loader provides a fallback: when a template can't be found
by standard loaders (filesystem, app_directories), it looks in the pre-generated
`templates_embedded.py` module where all templates are stored as Python strings.

IMPORTANT: The import is at the top level (not nested in a function) so that
Vercel's Python static dependency analyzer can detect it and include the
module in the serverless function bundle.

Usage (in settings):
    TEMPLATES = [{
        ...
        'OPTIONS': {
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'apps.esppa.template_loader.EmbeddedTemplateLoader',
            ],
        },
    }]
"""

import logging
from typing import Iterator

from django.template import TemplateDoesNotExist
from django.template.loaders.base import Loader

# Static import — Vercel's Python dependency analyzer detects module-level
# imports. DO NOT move this inside a function or try/except block.
try:
    from apps.esppa import templates_embedded as _embedded_templates_module
except ImportError:
    _embedded_templates_module = None

logger = logging.getLogger(__name__)


class EmbeddedTemplateLoader(Loader):
    """Loads templates from the pre-generated templates_embedded.py module.

    This loader is a LAST RESORT fallback — it only activates when standard
    loaders (filesystem, app_directories) fail to find a template.

    Templates are stored as string constants in a Python module generated by
    `build_embedded_templates.py`, ensuring they are always included in the
    Vercel serverless bundle.
    """

    def get_template_sources(self, template_name: str) -> Iterator[str]:
        """Yield the template_name as a pseudo-source for matching."""
        if _embedded_templates_module is None:
            return
        templates = getattr(_embedded_templates_module, 'TEMPLATES', {})
        if template_name in templates:
            yield template_name

    def get_contents(self, template_name: str) -> str:
        """Return the template content from the embedded module."""
        if _embedded_templates_module is not None:
            templates = getattr(_embedded_templates_module, 'TEMPLATES', {})
            if template_name in templates:
                logger.debug("Loaded embedded template: %s", template_name)
                return templates[template_name]
        raise TemplateDoesNotExist(template_name)


class EmbeddedTemplateLoader(Loader):
    """Loads templates from the pre-generated templates_embedded.py module.

    This loader is a LAST RESORT fallback — it only activates when standard
    loaders (filesystem, app_directories) fail to find a template.

    Templates are stored as string constants in a Python module generated by
    `build_embedded_templates.py`, ensuring they are always included in the
    Vercel serverless bundle.
    """

    def get_template_sources(self, template_name: str) -> Iterator[str]:
        """Yield the template_name as a pseudo-source for matching."""
        templates = _get_embedded_templates()
        if template_name in templates:
            yield template_name

    def get_contents(self, template_name: str) -> str:
        """Return the template content from the embedded module."""
        templates = _get_embedded_templates()
        if template_name in templates:
            logger.debug("Loaded embedded template: %s", template_name)
            return templates[template_name]
        raise TemplateDoesNotExist(template_name)
