"""
Custom template loader that reads templates from the embedded Python module.

Vercel's Python runtime does not reliably include .html files in the serverless
function bundle. This loader provides a fallback: when a template can't be found
by standard loaders (filesystem, app_directories), it looks in the pre-generated
`templates_embedded.py` module where all templates are stored as Python strings.

Usage (in settings):
    TEMPLATES = [{
        ...
        'OPTIONS': {
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'apps.esppa.template_loader.EmbeddedTemplateLoader',
            ],
        },
    }]
"""

import importlib.util
import logging
import os
import sys
from typing import Iterator

from django.template import TemplateDoesNotExist
from django.template.loaders.base import Loader

logger = logging.getLogger(__name__)

# Module-level cache for the embedded templates
_embedded_templates_cache = None


def _get_embedded_templates():
    """
    Load embedded templates from templates_embedded.py.

    Strategy (tried in order):
    1. Import as Python module via module name
    2. Load from file path directly (bypasses sys.path issues)
    3. Fall back to hardcoded inline dict (last resort)
    """
    global _embedded_templates_cache
    if _embedded_templates_cache is not None:
        return _embedded_templates_cache

    templates = {}

    # Strategy 1: Import via module name (standard approach)
    try:
        from apps.esppa import templates_embedded as _m
        templates = _m.TEMPLATES
        logger.info("Loaded embedded templates via module import (%d templates)", len(templates))
        _embedded_templates_cache = templates
        return templates
    except Exception as exc:
        logger.warning("Module import failed: %s: %s", type(exc).__name__, exc)

    # Strategy 2: Load from file path directly (bypasses Python path issues)
    if not templates:
        try:
            # Resolve path relative to this file's location
            loader_dir = os.path.dirname(os.path.abspath(__file__))
            embedded_path = os.path.join(loader_dir, 'templates_embedded.py')
            if os.path.exists(embedded_path):
                spec = importlib.util.spec_from_file_location(
                    'templates_embedded_loader', embedded_path
                )
                _m = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(_m)
                templates = getattr(_m, 'TEMPLATES', {})
                logger.info(
                    "Loaded embedded templates via file path (%d templates)",
                    len(templates)
                )
                _embedded_templates_cache = templates
                return templates
            else:
                logger.warning(
                    "templates_embedded.py not found at: %s", embedded_path
                )
        except Exception as exc:
            logger.warning("File load failed: %s: %s", type(exc).__name__, exc)

    # Strategy 3: Extract from sys.modules (already imported by build script)
    if not templates:
        try:
            _m = sys.modules.get('apps.esppa.templates_embedded')
            if _m and hasattr(_m, 'TEMPLATES'):
                templates = _m.TEMPLATES
                logger.info("Loaded from sys.modules (%d templates)", len(templates))
                _embedded_templates_cache = templates
                return templates
        except Exception as exc:
            logger.warning("sys.modules lookup failed: %s: %s", type(exc).__name__, exc)

    _embedded_templates_cache = templates
    return templates


class EmbeddedTemplateLoader(Loader):
    """Loads templates from the pre-generated templates_embedded.py module.

    This loader is a LAST RESORT fallback — it only activates when standard
    loaders (filesystem, app_directories) fail to find a template.

    Templates are stored as string constants in a Python module generated by
    `build_embedded_templates.py`, ensuring they are always included in the
    Vercel serverless bundle.
    """

    def get_template_sources(self, template_name: str) -> Iterator[str]:
        """Yield the template_name as a pseudo-source for matching."""
        templates = _get_embedded_templates()
        if template_name in templates:
            yield template_name

    def get_contents(self, template_name: str) -> str:
        """Return the template content from the embedded module."""
        templates = _get_embedded_templates()
        if template_name in templates:
            logger.debug("Loaded embedded template: %s", template_name)
            return templates[template_name]
        raise TemplateDoesNotExist(template_name)
